name: odm-platform CI/CD
on:
  release:
    types: [created]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set env # Extract version and branch from tag and save them as environment variables
        run: |
          echo "TAG_VERSION=$( echo ${{github.ref_name}} | sed 's/[^0-9.]//g' )" >> $GITHUB_ENV
          echo "BRANCH_NAME=$( echo ${{ github.event.base_ref }} | sed 's|refs/heads/||' )" >> $GITHUB_ENV
      - name: Update versions
        run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ env.TAG_VERSION }}

      - name: Push new version
        run: |
          git tag -d ${{ env.TAG_VERSION }}
          git push origin :refs/tags/${{ env.TAG_VERSION }}

          git config user.name "github-workflows-version-updater"
          git config user.email "<>"
          git commit -am "Update pom versions to ${{ env.TAG_VERSION }}"
          git tag ${{ env.TAG_VERSION }}

          git push origin ${{ env.TAG_VERSION }}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
